// Code generated by tools/gen.go; DO NOT EDIT.

package game

// The piece colors drawn in client/assets.
var (
	xColors = []string{"#AF3029", "#BF616A", "#C01C28", "#C33027", "#C34043", "#C6262E", "#C84053", "#CC2222", "#CC241D", "#CC6666", "#CD3131", "#CF6A4C", "#D0D0D0", "#D14D41", "#D32F2F", "#D73737", "#DC322F", "#E05C5C", "#E06C75", "#E67E80", "#E74C3C", "#E95678", "#EA6962", "#ED333B", "#EF5350", "#F07178", "#F38BA8", "#F44336", "#F77669", "#F7768E", "#F85552", "#F92672", "#FB4934", "#FF2D55", "#FF5252", "#FF5555", "#FF6B35", "#FF6B6B"}
	oColors = []string{"#006688", "#0097A7", "#00BCD4", "#06B6D4", "#11A8CD", "#1C71D8", "#24837B", "#28BFFF", "#2AA198", "#2D9EAF", "#33859D", "#3498DB", "#35A77C", "#3AA99F", "#4ECDC4", "#50C8C8", "#56B6C2", "#59E3E3", "#5AC8FA", "#62A0EA", "#6693BF", "#66D9E8", "#689D6A", "#7AA89F", "#7DCFFF", "#7FDBCA", "#83C092", "#88C0D0", "#89B482", "#89DCEB", "#8ABEB7", "#8BE9FD", "#8EC07C", "#909090", "#95E6CB", "#9B859D", "#FFB347"}
)
