//go:build ignore

// gen draws Tic-tac-toe's client files: an X in every red and an O in every
// cyan that Concord's built-in themes use (so pieces match whatever theme a
// viewer picked), and its sounds. It also writes game/pieces_gen.go, the
// list of colors drawn. Run from the repo root: go run tools/gen.go
package main

import (
	"encoding/binary"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/JMThomas00/Concord/sdk/arcade"
)

// The reds and cyans of Concord's built-in themes (internal/themes/themes),
// plus stand-ins for the terminal-default theme's palette entries.
var reds = []string{
	"#AF3029", "#BF616A", "#C33027", "#C34043", "#CC6666", "#CF6A4C", "#D0D0D0", "#DC322F", "#E05C5C",
	"#E06C75", "#E67E80", "#E95678", "#EA6962", "#ED333B", "#EF5350", "#F07178", "#F38BA8", "#F44336",
	"#F77669", "#F7768E", "#F92672", "#FB4934", "#FF2D55", "#FF5252", "#FF5555", "#FF6B35", "#FF6B6B",
	"#C01C28", "#C6262E", "#C84053", "#CC2222", "#CC241D", "#D14D41", "#D32F2F", "#D73737", "#E74C3C",
	"#F85552", "#CD3131",
}

var cyans = []string{
	"#24837B", "#88C0D0", "#33859D", "#7AA89F", "#8ABEB7", "#9B859D", "#909090", "#2AA198", "#50C8C8",
	"#56B6C2", "#83C092", "#59E3E3", "#89B482", "#62A0EA", "#7FDBCA", "#95E6CB", "#89DCEB", "#00BCD4",
	"#06B6D4", "#7DCFFF", "#66D9E8", "#8EC07C", "#5AC8FA", "#8BE9FD", "#FFB347", "#4ECDC4", "#1C71D8",
	"#28BFFF", "#6693BF", "#006688", "#689D6A", "#3AA99F", "#0097A7", "#2D9EAF", "#3498DB", "#35A77C",
	"#11A8CD",
}

const size = 160

func main() {
	reds, cyans := unique(reds), unique(cyans)
	for _, c := range reds {
		piece(filepath.Join("client", "assets", "x-"+name(c)+".png"), parse(c), func(x, y float64) float64 {
			return math.Min(segment(x, y, .26, .26, .74, .74), segment(x, y, .74, .26, .26, .74))
		})
	}
	for _, c := range cyans {
		piece(filepath.Join("client", "assets", "o-"+name(c)+".png"), parse(c), func(x, y float64) float64 {
			return math.Abs(math.Hypot(x-.5, y-.5) - .27)
		})
	}

	sound("move.wav", .09, func(t float64) float64 {
		// a soft wooden tap
		return .55*math.Sin(2*math.Pi*196*t)*math.Exp(-t*55) + .15*math.Sin(2*math.Pi*784*t)*math.Exp(-t*120)
	})
	sound("win.wav", .95, func(t float64) float64 {
		// up a major chord, each note ringing out
		v := 0.0
		for i, f := range []float64{523.25, 659.25, 783.99, 1046.5} {
			if s := t - float64(i)*.11; s >= 0 {
				v += .22 * (math.Sin(2*math.Pi*f*s) + .3*math.Sin(4*math.Pi*f*s)) * math.Exp(-s*5)
			}
		}
		return v
	})
	sound("draw.wav", .6, func(t float64) float64 {
		// two gentle notes, the second lower: even
		v := 0.0
		for i, f := range []float64{587.33, 493.88} {
			if s := t - float64(i)*.16; s >= 0 {
				v += .25 * math.Sin(2*math.Pi*f*s) * math.Exp(-s*6)
			}
		}
		return v
	})

	// The Concord Arcade sound kit: menu blips, the coin, the fanfare.
	check(arcade.WriteSoundKit("client"))

	var b strings.Builder
	b.WriteString("// Code generated by tools/gen.go; DO NOT EDIT.\n\npackage game\n\n")
	b.WriteString("// The piece colors drawn in client/assets.\nvar (\n")
	fmt.Fprintf(&b, "\txColors = %s\n\toColors = %s\n)\n", list(reds), list(cyans))
	check(os.WriteFile(filepath.Join("game", "pieces_gen.go"), []byte(b.String()), 0o644))
	fmt.Printf("%d X and %d O pieces, 3 sounds and the arcade kit\n", len(reds), len(cyans))
}

func unique(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, c := range in {
		c = strings.ToUpper(c)
		if !seen[c] {
			seen[c] = true
			out = append(out, c)
		}
	}
	sort.Strings(out)
	return out
}

func name(hex string) string { return strings.ToLower(strings.TrimPrefix(hex, "#")) }

func list(cs []string) string {
	// The Concord Arcade sound kit: menu blips, the coin, the fanfare.
	check(arcade.WriteSoundKit("client"))

	var b strings.Builder
	b.WriteString("[]string{")
	for i, c := range cs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", c)
	}
	b.WriteString("}")
	return b.String()
}

func parse(hex string) color.NRGBA {
	var r, g, b uint8
	fmt.Sscanf(hex, "#%02x%02x%02x", &r, &g, &b)
	return color.NRGBA{r, g, b, 255}
}

// piece draws a stroke (dist is the distance to it, in cell units) with
// anti-aliased edges, a lighter core and a soft glow, on transparency.
func piece(path string, c color.NRGBA, dist func(x, y float64) float64) {
	img := image.NewNRGBA(image.Rect(0, 0, size, size))
	const width, glow = .062, .085
	light := func(v uint8) uint8 { return uint8(math.Min(255, float64(v)+(255-float64(v))*.35)) }
	for py := 0; py < size; py++ {
		for px := 0; px < size; px++ {
			var a, core float64
			for sy := 0; sy < 4; sy++ { // 4×4 supersampling
				for sx := 0; sx < 4; sx++ {
					x := (float64(px) + (float64(sx)+.5)/4) / size
					y := (float64(py) + (float64(sy)+.5)/4) / size
					d := dist(x, y)
					switch {
					case d < width:
						a++
						core += math.Max(0, 1-d/(width*.55)) // brightest along the middle
					case d < width+glow:
						a += .22 * math.Pow(1-(d-width)/glow, 2)
					}
				}
			}
			a /= 16
			core = math.Min(1, core/16*2.2)
			if a > 0 {
				mix := func(base uint8) uint8 { return uint8(float64(base)*(1-core*.6) + float64(light(base))*core*.6) }
				img.SetNRGBA(px, py, color.NRGBA{mix(c.R), mix(c.G), mix(c.B), uint8(a * 255)})
			}
		}
	}
	write(path, func(f *os.File) error { return png.Encode(f, img) })
}

// sound writes a 16-bit mono 48 kHz WAV.
func sound(file string, seconds float64, wave func(t float64) float64) {
	const rate = 48000
	n := int(seconds * rate)
	data := make([]byte, 0, n*2)
	for i := 0; i < n; i++ {
		t := float64(i) / rate
		v := wave(t) * math.Min(1, (seconds-t)*40) // fade out the last 25 ms
		data = binary.LittleEndian.AppendUint16(data, uint16(int16(math.Max(-1, math.Min(1, v))*32767)))
	}
	h := []byte("RIFF")
	h = binary.LittleEndian.AppendUint32(h, uint32(36+len(data)))
	h = append(h, "WAVEfmt "...)
	for _, v := range []uint32{16} {
		h = binary.LittleEndian.AppendUint32(h, v)
	}
	h = binary.LittleEndian.AppendUint16(h, 1)
	h = binary.LittleEndian.AppendUint16(h, 1)
	h = binary.LittleEndian.AppendUint32(h, rate)
	h = binary.LittleEndian.AppendUint32(h, rate*2)
	h = binary.LittleEndian.AppendUint16(h, 2)
	h = binary.LittleEndian.AppendUint16(h, 16)
	h = append(h, "data"...)
	h = binary.LittleEndian.AppendUint32(h, uint32(len(data)))
	write(filepath.Join("client", "sounds", file), func(f *os.File) error { _, err := f.Write(append(h, data...)); return err })
}

// segment is the distance from (x, y) to the segment (ax, ay)-(bx, by).
func segment(x, y, ax, ay, bx, by float64) float64 {
	dx, dy := bx-ax, by-ay
	t := math.Max(0, math.Min(1, ((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy)))
	return math.Hypot(x-(ax+t*dx), y-(ay+t*dy))
}

func write(path string, fn func(*os.File) error) {
	check(os.MkdirAll(filepath.Dir(path), 0o755))
	f, err := os.Create(path)
	check(err)
	defer f.Close()
	check(fn(f))
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen:", err)
		os.Exit(1)
	}
}
